# Generated by Django 4.2.8 on 2024-04-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='equipamento_responsavel',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='equipamento_responsavel',
            field=models.ManyToManyField(related_name='responsaveis', to='appcd.equipamento'),
        ),
    ]
