# Generated by Django 4.2.8 on 2024-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcd', '0002_remove_responsavel_equipamento_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Ativo'), ('I', 'Inativo'), ('N', 'Nenhuma das opções')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(max_length=50, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='rg',
            field=models.CharField(max_length=50, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefone'),
        ),
    ]
