# Generated by Django 5.0.3 on 2024-03-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_devicehub', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipamento',
            unique_together={('imei1', 'imei2', 'serial')},
        ),
        migrations.AlterUniqueTogether(
            name='responsavel',
            unique_together={('rg', 'cpf')},
        ),
    ]
