# Generated by Django 5.0.3 on 2024-04-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devicehub', '0002_alter_equipamento_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='equipamento_responsavel',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='equipamento_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_devicehub.equipamento', verbose_name='Dispositivo'),
        ),
    ]
