# Generated by Django 5.0.3 on 2024-04-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_devicehub', '0003_remove_responsavel_equipamento_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='equipamento_responsavel',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='equipamento_responsavel',
            field=models.ManyToManyField(related_name='responsaveis', to='app_devicehub.equipamento'),
        ),
    ]
