# Generated by Django 4.2.8 on 2024-02-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TablesDataWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('createscript', models.TextField(verbose_name='Script de Criação')),
                ('status', models.CharField(max_length=1, verbose_name='Status')),
                ('alteruser', models.CharField(max_length=30, verbose_name='Usuário Alteração')),
                ('datealter', models.DateTimeField(verbose_name='Data Alteração')),
            ],
        ),
    ]
