# Generated by Django 4.2.8 on 2024-02-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TablesDataWarehouse',
            new_name='appetd001',
        ),
    ]
