# Generated by Django 4.2.8 on 2024-02-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0002_rename_tablesdatawarehouse_appetd001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appetd001',
            new_name='TabelasArmazenagens',
        ),
    ]
