# Generated by Django 4.2.8 on 2024-02-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0003_rename_appetd001_tabelasarmazenagens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TabelasArmazenagens',
            new_name='TabelaArmazenagem',
        ),
    ]
