# Generated by Django 4.2.8 on 2024-02-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0005_rename_tabelaarmazenagem_tabledatawarehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledatawarehouse',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Status'),
        ),
    ]
