# Generated by Django 4.2.8 on 2024-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0006_alter_tabledatawarehouse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledatawarehouse',
            name='type',
            field=models.CharField(choices=[('D', 'Dimensão'), ('F', 'Fato')], default='D', max_length=1, verbose_name='Tipo'),
        ),
    ]
