# Generated by Django 4.2.8 on 2024-02-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0007_tabledatawarehouse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledatawarehouse',
            name='type',
            field=models.CharField(choices=[('D', 'Dimensão'), ('F', 'Fato')], max_length=1, verbose_name='Tipo'),
        ),
    ]
