# Generated by Django 4.2.8 on 2024-02-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0008_alter_tabledatawarehouse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledatawarehouse',
            name='alteruser',
            field=models.IntegerField(verbose_name='Usuário Alteração'),
        ),
        migrations.AlterField(
            model_name='tabledatawarehouse',
            name='datealter',
            field=models.DateField(auto_now=True, verbose_name='Data Alteração'),
        ),
    ]
