# Generated by Django 4.2.8 on 2024-03-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0009_alter_tabledatawarehouse_alteruser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabledatawarehouse',
            options={'ordering': ['id'], 'verbose_name_plural': 'Tabelas'},
        ),
        migrations.CreateModel(
            name='SelectTablesDataExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('selectinitial', models.TextField(verbose_name='Select Inicial')),
                ('selectpartial', models.TextField(verbose_name='Select Parcial')),
                ('partial', models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=1, verbose_name='Executa select parcial?')),
                ('type', models.CharField(choices=[('D', 'Dimensão'), ('F', 'Fato')], max_length=1, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Status')),
                ('alteruser', models.IntegerField(verbose_name='Usuário Alteração')),
                ('datealter', models.DateField(auto_now=True, verbose_name='Data Alteração')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appetd.tabledatawarehouse')),
            ],
            options={
                'verbose_name_plural': 'Selects',
                'ordering': ['id'],
            },
        ),
    ]
