# Generated by Django 4.2.8 on 2024-03-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0010_alter_tabledatawarehouse_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecttablesdataextraction',
            old_name='tabela',
            new_name='table',
        ),
    ]
