# Generated by Django 4.2.8 on 2024-03-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appetd', '0012_alter_selecttablesdataextraction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecttablesdataextraction',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appetd.tabledatawarehouse'),
        ),
    ]
